version: "3"
services:
    bot:
        build: https://github.com/PloxHost-LLC/community-bot.git#main
        pull_policy: always
        restart: unless-stopped
        depends_on:
            - mongodb
        links:
            - mongodb
        networks:
            - backend
        environment:
            - prefix=?
            - bot_token=Njk2NDMwNDUwMTQyMzQ3MzU3.XoonZg.WbjR_7X96-E-r_9z1s2fpJEoAOk
            - connection_string=mongodb://root:root@mongodb
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongodb_combot:/data/db
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
    mongodb_combot: {}
