version: "3"
services:
    bot:
        image: registry.plox.host/ploxhost/communitybot:latest
        pull_policy: always
        restart: unless-stopped
        depends_on:
            - mongodb
        links:
            - mongodb
        networks:
            - backend
        env_file: 
            - .env
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongodb_combot:/data/db
        expose:
            - "27017"
        env_file: 
            - .env
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
    mongodb_combot: {}
