version: "3"
services:
    bot:
        image: registry.plox.host/ploxhost/communitybot:latest
        restart: unless-stopped
        depends_on:
            - mongodb
        links:
            - mongodb
        networks:
            - backend
        environment:
            - prefix=?
            - bot_token=TOKEN
            - connection_string=mongodb://root:root@mongodb
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongodb_combot:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - backend
networks:
    backend:
        driver: bridge

volumes:
    mongodb_combot: {}
